# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 10:23
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200226_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
