# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200226_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
